# Generated by Django 4.2.2 on 2023-07-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.FloatField(),
        ),
    ]
