# Generated by Django 4.2.4 on 2023-08-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0002_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='operation_name',
            field=models.CharField(default='no_operation_defined', max_length=25),
        ),
    ]
