[tool]
[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "liquidsnake", email = "bentsoft365@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
license = {text = "MIT"}
